development:
  adapter: <%= ENV["DB_ADAPTER"] %>
  encoding: utf8
  reconnect: false
  database: <%= ENV["DB_NAME_DEVELOPMENT"] %>
  pool: 5
  username: <%= ENV["DB_LOGIN"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

test:
  adapter: <%= ENV["DB_ADAPTER"] %>
  encoding: utf8
  reconnect: false
  database: <%= ENV["DB_NAME_TEST"] %>
  pool: 5
  username: <%= ENV["DB_LOGIN"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

production:
  adapter: <%= ENV["DB_ADAPTER"] %>
  encoding: utf8
  reconnect: false
  database: <%= ENV["DB_NAME_PRODUCTION"] %>
  pool: 5
  username: <%= ENV["DB_LOGIN"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
